### ISSUE TITLE
http://jp.scala-users.org/ is not found

### ISSUE THREAD

**Issue by tkawachi** [scalajp/scalajp#11]
なぜでしょう..?
![2013-10-03 9 08 19 am](https://f.cloud.github.com/assets/22657/1258503/eef70a80-2bbf-11e3-9f3b-173647e9a6ec.png)

**Comment by xuwei-k** [comment]
単純に #10 の、このコミット d7cf3165218a のせいだと思います。 /cc @kmizu @osiire
revertすればなおるはず

**Comment by tkawachi** [comment]
消しました。

**Comment by kmizu** [comment]
@xuwei-k @tkawachi Thanks!
