### ISSUE TITLE
ニュースが更新されていない

### ISSUE THREAD

**Issue by tkawachi** [scalajp/scalajp#13]
ScalaMatsuri 運営会議の待ち時間に話題に出たのですが、ニュースで一番新しいのが 2.9.3 RC1 というのは初めて Scala に触れようという人をミスリードするでしょう。
- 消しても良いのではないか。
- Twitter のウィジェットにすると良いのではないか。

などの声がありました。

**Comment by xuwei-k** [comment]
少なくともトップページに 2.9 があるのは残念なので、たしかに表示しないほうがよさそう

**Comment by tkawachi** [comment]
他の選択肢として
- 更新する

というのもあります。はい。

**Comment by kmizu** [comment]
Twitterのウィジェット案に +1

**Comment by kmizu** [comment]
ニュース更新に関しては、再度やったとしても、結局本家と一体でやらないとどっかでモチベーションが一度下がると追従し損ねてそのままになってしまうので、今後はやらないでよいかなと思いました。

**Comment by kmizu** [comment]
というか、この辺は私が提案すべき事だったかもしれません。

**Comment by tkawachi** [comment]
Twitter のウィジェットだとすると何を表示するのがいいんですかね？
- @scala_jp のつぶやき
- 何か Hashtag を用意してそれを含むつぶやき

のどちらかでしょうか？

**Comment by mhanada** [comment]
ちょうど話がでてたんですね。すみませんほったらかしで。
（これみて翻訳したわけじゃないです・・・。）

**Comment by xuwei-k** [comment]
https://github.com/scalajp/scalajp/pull/55
