### ISSUE TITLE
markdownの設定変更

### ISSUE THREAD

**Issue by xuwei-k** [scalajp/scalajp#25]
久しぶりにpull reqをmergeしてgh-pagesのビルドが走ったら、以下の様なメール来たのでどうにかする

```
The page build completed successfully, but returned the following warning:

You are currently using the 'rdiscount' Markdown engine, which will not be supported on GitHub Pages after May 1st. At that time, your site will use 'kramdown' for markdown rendering instead. To suppress this warning, remove the 'markdown' setting in your site's '_config.yml' file and confirm your site renders as expected. For more information, see https://help.github.com/articles/updating-your-markdown-processor-to-kramdown.

GitHub Pages was recently upgraded to Jekyll 3.0. It may help to confirm you're using the correct dependencies:

  https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can contact us by replying to this email.
```

**Comment by kmizu** [comment]
たぶん、kramdownにしても問題なさそうですが、ローカルでいったん試してみてからですかね…。

**Comment by kmizu** [comment]
ちょっと調べてみたのですが、`github-pages` gemの依存（最新バージョンでも）に`rdiscount`が入っていて、よくわからないですね。同時に`kramdown`にも依存してるし…。

https://rubygems.org/gems/github-pages

**Comment by kmizu** [comment]
あー、そうか。

https://github.com/scalajp/scalajp/blob/gh-pages/_config.yml 

で使うmarkdownエンジンを`rdiscount`にしてるけど、それがまずいってことか。

**Comment by kmizu** [comment]
markdownエンジンを手元で`kramdown`に変更したところ、表示が崩れる現象が発生。

どうやら、`kramdown`では、
- 見出しの中にリンクを貼れない？
- `####`をちゃんと認識してくれない？

辺りの問題がある模様。どうしたものか…

<img width="1057" alt="example" src="https://cloud.githubusercontent.com/assets/97326/14815480/941b6e08-0be6-11e6-9e40-5f1e19889f78.png">

**Comment by xuwei-k** [comment]
> ####をちゃんと認識してくれない？

さすがに全く認識しないことはなさそうだから、前後の改行とかそういう関係ですかね？(適当な予想)

**Comment by xuwei-k** [comment]
もしくは `##` のあとの空白とか？

**Comment by kmizu** [comment]
> 前後の改行

これ、当たりでした。

**Comment by xuwei-k** [comment]
https://github.com/scalajp/scalajp/pull/27
