### ISSUE TITLE
「日本Scalaユーザーズグループ」公式ページの整理

### ISSUE THREAD

**Issue by kmizu** [scalajp/scalajp#38]
## 背景

- http://jp.scala-users.org/ のページの内容がほとんどobsoleteになっている
  - Scala初心者がみたときに、変な印象持ちそう（最近は、このページがヒットすることも少なくなってそうですが）
- 「日本Scalaユーザーズグループ」という任意団体が実質的に機能していない
  - Japan Scala Association (JSA) だったり、Scala関西だったり、Scala福岡だったり、に分かれてる
-  日本独自に情報を更新するのはメンテナンスコストが高い

## 提案

- 低めのメンテナンスコストで各種情報へのリンクを提供するだけのサイトにする
  - 「協賛」「ScalaJPウィキ」「Scala関係リンク集」「技術記事」「ニュース」は消す
  - トップページにはニュース以外を持ってくる
  - 発起人などは実態にそぐわなくなっているので削除

**Comment by aoiroaoino** [comment]
> 「日本Scalaユーザーズグループ」という任意団体が実質的に機能していない
> Japan Scala Association (JSA) だったり、Scala関西だったり、Scala福岡だったり、に分かれてる

ここが代表/集約/コミュニティの総意(?) ではないので、賛成です。「国内ユーザーグループ」等の項目を設けて、各地の各コミュニティの代表ページへ移譲するのがいいかなと思いました。

**Comment by kmizu** [comment]
意見ありがとうございます。ちょっと、他のタスクがあるので、着手が先になりそうですが、予定にいれておきます。

**Comment by ishibashi-stb** [comment]
環境の変化によって果たすべき役割が変わったと考えて以下のように目的を変えてはどうでしょうか
・「日本語圏でScalaに興味を持った人」へ向けて「国内外のScalaコミニュティを案内するホームページ」

**Comment by xuwei-k** [comment]
更新したいモチベーションや、やりたい人や、やるコストとか考えると、
基本的にはメンテコストすごく減らす方向で、そもそも極論としてはページ自体ほぼcloseくらいなノリで、(少なくとも一旦)ほぼメンテが必要なくなるサイトにしてしまっていいんじゃないかなぁ

**Comment by ishibashi-stb** [comment]
クローズは対外的にScalaが衰退しているというメッセージを送ってしまうので避けたいんですよね。
「Scalaのコミニュニティはどこにあるの？」という疑問は入門者にとってはよくあるものだし、
多の言語やってるひとでScalaを始めようしたときに「Scala ユーザー グループ 日本」などで検索することはメジャーなユースケースだと思うんですよ。
なので、コスト少なく、かつ現在こぼれているニーズを拾う方法として上記の案を考えました。

**Comment by kmizu** [comment]
@ishibashi-stb なるほど。確かに、対外的なメッセージ考えると、closeは微妙かもしれません。それで、提案の通りの「国内外のScalaコミニュティを案内するホームページ」というのはありなのかもとおもう一方で、リンク先がobsoleteになっていたら、それはそれで負の印象を与えそうなんですよね。そういう事を考えると、英語版公式サイトへのリンクと、賞味期限がかなり長めの情報のみを乗っけるが現実的かなと考えています。

この辺、それこそ、多少のお金を払って外注可能であるならいいとおもうんですが、ボランティアベースで維持し続けるのが、特にモチベーションの面から難しいというのが、活動を続けてきて思ったことですね。

**Comment by xuwei-k** [comment]
ここまで放置したらcloseもたいして変わらないのでは、くらいな気持ちもあり・・・

**Comment by kmizu** [comment]
放置されるだけなら、見た人は「このサイトは更新が追いついていないんだな」とおもうことはあるかもしれないですが、明確にcloseすると、「何らかの事情でcloseせざるを得なかった」というメッセージになる気がしてて、なら、継続的なメンテが要らない前提で、一度だけ作業するのも手かなと思っていたり。

ただ、これ「エイヤ」っと誰かが修正pull request投げて終了とした方が早そうな気がしてて、私も（おそらく）@xuwei-k さんも、そこまでする時間がないし（正確には、優先度が下がっている）、急ぎでもないしなーという気持ちになってるのかなと。

もし、 @ishibashi-stb さんにページ改修作業をお願い出来るなら、ここで、残すコンテンツだけを相談した上で、エイヤっとやっていただくのも手かなと思ってますが、どうでしょうか？

**Comment by ishibashi-stb** [comment]
やりますよ

**Comment by rysh** [comment]
@kmizu 残すコンテンツの相談すすんでます？
僕の独断と偏見でPRつくっちゃってそこからスタートしたほうがいいかもしれないですね。

**Comment by kmizu** [comment]
@rysh すいません。仕事とか私用でバタバタしてました。7月中はあまり時間が取れそうにないので、もし、やっていただけるなら、たたき台PR作っていただけると助かります。

**Comment by xuwei-k** [comment]
https://github.com/scalajp/scalajp/pull/55
