### ISSUE TITLE
scalajp公式ページ再スタートのためにミーティングを開く

### ISSUE THREAD

**Issue by kmizu** [scalajp/scalajp#56]
- 関連: https://github.com/scalajp/scalajp/pull/55
@xuwei-k さんの
> ほぼ全てが何年も前で古いし、これをやらないと結局誰もやらないまま放置されそうなので、もう一旦全部消して再スタートする

は凄いもっともだとおもうので、approverしてマージしました。

で、いったん再スタートのためのミーティングやりましょうという提案です。たぶん、オンラインミーティングで現状に関して出し合えば割とすぐ再出発出来そうな気がしますし。

さしあたって、[調整さんで予定](https://chouseisan.com/s?h=184f20f04bff4b2ba69237c5ee2ba713)作りました。平日の19:00スタートまたは21:00スタート（いずれもミーティング自体は1時間）で、サクサクと再スタートに当たって何を復活させるのか、あるいはどれは復活させないか議論したいと思います。

今度はちゃんとメンテの目処が立つものに限って復活させるという方向で行ければとおもうので、ページの再出発について参画したい方は上記から予定を入力していただけると助かります。

ちなみに、私の方はめっちゃ忙しい時期は一段落しましたし、今後数ヶ月は少なくともめっちゃ忙しくなるような予定は入れないつもりなので、積極的に音頭とるつもりです。

**Comment by xuwei-k** [comment]
前のissue https://github.com/scalajp/scalajp/issues/38 の議論の繰り返しになるけど、そもそも `日本Scalaユーザーズグループ` としてまとめる必然性があるものがあるか？というと、無いから放置された側面があると思うので、ミーティングを開いて決めることがあるか？というと・・・
(いや別にミーティング自体は参加できそうな人多ければやっていいと思いますが、自分はいずれにせよ参加しない可能性)

それ自体は、必ずしも悪い意味ではなく `日本Scalaユーザーズグループ` が出来た10年近く前？に比べたら、わざわざまとめなくても、情報がネットに溢れていると思うんですよね
(その情報が整理されてるかどうか？はともかく。とはいえインターネットなんてそんなもの、みたいな)


そうすると、単なるリンク集、みたいなページにするか？という話だったけど、 `リンク集` ですら別に `日本Scalaユーザーズグループ` としてまとめる必要あるのか？(必要あったらここまで放置されないのでは)みたいな気持ちになるので 🤔

**Comment by kmizu** [comment]
@xuwei-k 返信遅れました。@xuwei-k さんには既に十分（コミュニティ活動に限らず）ご協力いただいていますし、ミーティングについては、もしその気があれば……くらいの温度感です。

**日本Scalaユーザーズグループ**としてまとめる必要があるかというと、現在ではほぼないと言っていいかと思います。ただ、実用でよく使われている言語は（たとえば、[Ruby](https://www.ruby-lang.org/ja/)や[Python](https://www.python.jp/)）私の感覚では大抵日本語のポータルサイトみたいなのがあるよなという感覚がありまして。

もちろん、既にScala使い込んでたり、あるいは他言語に十分熟練してるユーザーが新しくScala始めようというときに、そういう情報は必要ではないと思います（Scala研修テキストもありますし、書籍としては実践Scala入門やコップ本がありますし）。

ただ、日本語ポータルサイトくらいはないと、「よし、Scala始めよう」というユーザーが「どうやって始めれば……」と知らない間に学ぶのを諦めてるってケースはままありそう、というのがメンテナンスにこだわってる理由です（Twitter見てると、たまに「Scalaどうやって始めればいいんだろう」みたいなつぶやきも見ますし）。

サイトのメンテナになり得る人たち（おそらく、このリポジトリで議論に参加するような人）は、サイトを必要としていないけど、本当のScala初学者は何らかの形でリンク集くらいは必要な人は多そうなので（こういうのは、初学者じゃなくなると気持ちを忘れてしまいがち故に、放置されがちになるのかなとも）、メンテナンスコストを最小限にした上で、半年一回くらい更新されればよし、くらいのリンク集はあった方が良さそうだなと考えてます。 cc @ishibashi-stb @aoiroaoino

**Comment by xuwei-k** [comment]
一定以上ちゃんと更新されるならもちろんあったほうがいいけど、一定以上うまく更新される仕組みを作る方法が特に・・・ 🤔 

まぁ、そもそもそういうのは大まかには気合というか個々のやる気次第であって、やってみないことにはわからないので、(今まで数年間放置されたけど再び)やってみるしかない、というのはあるが・・・

**Comment by kmizu** [comment]
@xuwei-k 仕組みづくりについてはおっしゃる通り、難しいですが、いっそのことJSA預かりにして、お金払って更新してもらう契約を（特にフリーランスでやってる人とか？）結ぶみたいな手段もとれるかもしれません（ちょっと次のJSA定期ミーティングで議題にあげてみようかと思います）。

あるいは、この機会にJSAとは別のなんか、日本Scalaユーザーズグループでなくてもあってもどっちでもいいですが、コミュニティに関する定例ミーティング（それこそ2か月に一回とかでも）設けるというのも手かと考えてます。チャットオンリーとかでもいいのですが、とにかく集まって報告する機会があれば多少は進捗しそうです。

最近実感するのですが、こういうやつで更新が滞る根本原因って「締め切りが存在しない」事が原因だと思うんですよね。ボランティア活動であっても。

**Comment by xuwei-k** [comment]
あえて論点があるとしたら、
Scala公式のサイトにある程度の公式ドキュメントの翻訳はあるので、それと被らないもの載せる？被らないものとは

- 単なるリンク集 or
- 翻訳じゃない独自コンテンツ？ or
- 翻訳だとしても公式よりこっちに独自に載せる利点があるならこっちに載せる？)

みたいなのくらい・・・。

あとは、どうせリソースをさくならば、もし、それこそ公式サイトでの翻訳のほうを頑張ったほうが良い、となったら、日本Scalaユーザーグループのページで頑張るのはあまり必要ないというか優先度下がる、とか

**Comment by kmizu** [comment]
@xuwei-k なるほど。確かに、リンク集でないものに仮にするなら、公式サイトでの翻訳を頑張るべきという話にはなりそうですね。ただ、そうなると、リソースがより必要になるのも間違いないので、安定して追従するなら外注＋ボランティアみたいな体勢の方が良いかもなーと思ったり。

**Comment by kmizu** [comment]
JSAミーティングで議題に出しましたが、
- いきなり外注はややリスク
  - ミスマッチの可能性
- 最初GitHub Wikiから始める
  - メンテナンスが軌道に乗ってきたら外注（？）
  - `scalajp/xxx` リポジトリを作る: （@kmizu タスク）
という感じになりました

**Comment by xuwei-k** [comment]
github wikiも、更新されてない?ものがあったような…
https://github.com/scalajp/scalajp.github.com/wiki

**Comment by kmizu** [comment]
@xuwei-k すっかり忘れてました……。その辺りも全部更地にして始めた方が良さそうです。

**Comment by kmizu** [comment]
@xuwei-k いったん更地にして、リンク集から作り始めました。 https://github.com/scalajp/scalajp.github.com/wiki というかメンテするのはリンク集だけでいい気もしてきましたが（陳腐化を防ぐには）。

**Comment by xuwei-k** [comment]
更新されてないというか、どうなればcloseするのか？が曖昧だから、一旦closeするか
